WebBanHang/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebBanHang.Models
{
    public class Product
    {
        public int Id { get; set; }
        [Required, StringLength(200)]
        public string Name { get; set; }
        public string? Description { get; set; }
        public double Price { get; set; }
        public string? ImageUrl { get; set; }
        public int CategoryId { get; set; }
        
      
        public virtual Category Category { set; get; } 
       
    }
}

WebBanHang/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebBanHang.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace WebBanHang.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hosting;
        public ProductController(ApplicationDbContext db, IWebHostEnvironment hosting)
        {
            _db = db;
            _hosting = hosting;
        }
        //trả về giao diện quản lí sản phẩm

        public IActionResult Index(int page = 1)
        {
            int pageSize = 3;
            var productList = _db.Products.Include(x => x.Category).ToList();
            var pagedProducts = productList.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.PageSum = Math.Ceiling((double)productList.Count / pageSize);
            ViewBag.CurrentPage = page;

            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_ProductListPartial", pagedProducts);
            }

            return View(pagedProducts);
        }


        public IActionResult Add()
        {

            ViewBag.CategoryList = _db.Categories.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });
            return View();
        }

        [HttpPost]
        public IActionResult Add(Product product, IFormFile ImageUrl)
        {
            if (ModelState.IsValid)
            {
                if (ImageUrl != null)
                {

                    product.ImageUrl = SaveImage(ImageUrl);
                }

                _db.Products.Add(product);
                _db.SaveChanges();
                TempData["success"] = "Product inserted success";
                return RedirectToAction("Index");
            }
            ViewBag.CategoryList = _db.Categories.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });
            return View();
        }

        public IActionResult Update(int id)
        {
            var product = _db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            ViewBag.CategoryList = _db.Categories.Select(x => new SelectListItem
            {

                Value = x.Id.ToString(),
                Text = x.Name
            });
            return View(product);
        }

        [HttpPost]
        public IActionResult Update(Product product, IFormFile ImageUrl)
        {
            if (ModelState.IsValid)
            {
                var existingProduct = _db.Products.Find(product.Id);
                if (ImageUrl != null)
                {

                    product.ImageUrl = SaveImage(ImageUrl);

                    if (!string.IsNullOrEmpty(existingProduct.ImageUrl))
                    {
                        var oldFilePath = Path.Combine(_hosting.WebRootPath, existingProduct.ImageUrl);
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }
                }
                else
                {
                    product.ImageUrl = existingProduct.ImageUrl;
                }

                existingProduct.Name = product.Name;
                existingProduct.Description = product.Description;
                existingProduct.Price = product.Price;
                existingProduct.CategoryId = product.CategoryId;
                existingProduct.ImageUrl = product.ImageUrl;
                _db.SaveChanges();
                TempData["success"] = "Product updated success";
                return RedirectToAction("Index");
            }
            ViewBag.CategoryList = _db.Categories.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });
            return View();
        }
        private string SaveImage(IFormFile image)
        {

            var filename = Guid.NewGuid().ToString() + Path.GetExtension(image.FileName);

            var path = Path.Combine(_hosting.WebRootPath, @"images/products");
            var saveFile = Path.Combine(path, filename);
            using (var filestream = new FileStream(saveFile, FileMode.Create))
            {
                image.CopyTo(filestream);
            }
            return @"images/products/" + filename;
        }


        public IActionResult Delete(int id)
        {
            var product = _db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var product = _db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            if (!String.IsNullOrEmpty(product.ImageUrl))
            {
                var oldFilePath = Path.Combine(_hosting.WebRootPath, product.ImageUrl);
                if (System.IO.File.Exists(oldFilePath))
                {
                    System.IO.File.Delete(oldFilePath);
                }
            }

            _db.Products.Remove(product);
            _db.SaveChanges();
            TempData["success"] = "Product deleted success";
            //chuyen den action index
            return RedirectToAction("Index");
        }
    }
}

WebBanHang/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebBanHang.Areas.Customer.Models;
using WebBanHang.Models;

namespace WebBanHang.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CartController(ApplicationDbContext db) { _db = db; }

        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetJson<Cart>("CART") ?? new Cart();
            return View(cart);
        }

        public IActionResult AddToCart(int productId)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                var cart = HttpContext.Session.GetJson<Cart>("CART") ?? new Cart();
                cart.Add(product, 1);
                HttpContext.Session.SetJson("CART", cart);
            }
            return RedirectToAction("Index");
        }


        public IActionResult GetQuantityOfCart()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("CART");
            if (cart != null)
            {
                return Json(new { qty = cart.Quantity });

            }
            return Json(new { qty = 0 });
        }


        public IActionResult Update(int productId, int qty)
        {
            var cart = HttpContext.Session.GetJson<Cart>("CART");
            if (cart != null)
            {
                cart.Update(productId, qty);
                HttpContext.Session.SetJson("CART", cart);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Remove(int productId)
        {
            var cart = HttpContext.Session.GetJson<Cart>("CART");
            if (cart != null)
            {
                cart.Remove(productId);
                HttpContext.Session.SetJson("CART", cart);
            }
            return RedirectToAction("Index");
        }
    }

}

WebBanHang/Areas/Customer/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using WebBanHang.Models;
using WebBanHang.Areas.Customer.Models;

namespace WebBanHang.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ProductController : Controller
    {
        private ApplicationDbContext _db;
        public ProductController(ApplicationDbContext db)

        {
            _db = db;
        }
        public IActionResult Index(int catid = 1)

        {
            var dsSanPham = _db.Products.Include(x => x.Category).Where(x => x.CategoryId == catid).ToList();
            return View(dsSanPham);
        }
        public IActionResult GetCategory()
        {
            var dsTheLoai = _db.Categories
      .Select(c => new CategoryWithCountVM
      {
          Id = c.Id,
          Name = c.Name,
          ProductCount = _db.Products.Count(p => p.CategoryId == c.Id)
      })
      .ToList();

            return PartialView("CategoryPartial", dsTheLoai);
        }


    }
}

WebBanHang/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using WebBanHang.Models;



namespace WebBanHang.Controllers
{
    public class ProductController : Controller
    {
        private ApplicationDbContext _db;
        public ProductController(ApplicationDbContext db)

        {
            _db = db;
        }
        public IActionResult Index(int catid = 1)

        {
            var dsSanPham = _db.Products.Include(x => x.Category).Where(x => x.CategoryId == catid).ToList();
            return View(dsSanPham);
        }
        public IActionResult GetCategory()
        {
            var dsTheLoai = _db.Categories.ToList();
            return PartialView("CategoryPartial", dsTheLoai);
        }

    }
}

WebBanHang/Areas/Customer/Views/Product/CategoryPartial.cshtml
@model List<WebBanHang.Areas.Customer.Models.CategoryWithCountVM>


<ul class="list-group">
    @foreach (var c in Model)
    {
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="@Url.Action("Index", "Product", new { catid = c.Id })" class="text-decoration-none text-dark">
                @c.Name
            </a>
            <span class="badge bg-secondary rounded-pill">@c.ProductCount</span>
        </li>
    }
</ul>

WebBanHang/Areas/Customer/Views/Product/Index.cshtml
@model List<WebBanHang.Models.Product>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <!-- Cột trái: Danh sách thể loại -->
    <div class="col-md-3">
        <h3>DANH MỤC</h3>
        <div id="Category-List">
            <!-- Danh sách thể loại sẽ được load bằng AJAX -->
        </div>
    </div>

    <!-- Cột phải: Danh sách sản phẩm -->
    <div class="col-md-9">
        <h3>SẢN PHẨM</h3>
        <partial name="_ProductPartial" model="Model" />
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#Category-List").load("/Customer/Product/GetCategory");
        });
    </script>
}

WebBanHang/Areas/Customer/Views/Product/_ProductPartial.cshtml
@model List<WebBanHang.Models.Product>

@if (Model != null && Model.Count > 0)
{
    <div class="row">
        @foreach (var p in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    @if (!string.IsNullOrEmpty(p.ImageUrl))
                    {
                        <img src="@p.ImageUrl" class="card-img-top" alt="@p.Name" style="height: 340px; object-fit: cover;" />
                    }

                    <div class="card-body text-center">
                        <h5 class="card-title">@p.Name</h5>
                        <p class="card-text">
                            <strong>Giá:</strong> @p.Price.ToString("N0") đ
                        </p>
                    </div>

                    <div class="card-footer d-flex justify-content-center gap-2">
                        <a href="#" class="btn btn-sm btn-outline-dark">Chi tiết</a>
                        <a asp-area="Customer" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@p.Id" class="btn btn-sm btn-outline-primary">Thêm vào giỏ</a>

                    </div>

                    <div class="card-footer text-muted text-center" style="font-size: 0.9rem;">
                        Thể loại: @p.Category?.Name
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="alert alert-info">
        Không có sản phẩm nào được hiển thị.
    </div>
}